version: '3.7'
services:
  ## Provide build instructions for all i40-aas images
  i40-aas-onboarding-skill:
    build:
      context: apps/onboarding-skill
      network: host
      dockerfile: ../../docker/onboarding-skill/Dockerfile
  i40-aas-https-endpoint:
    build:
      context: apps/https-endpoint
      network: host
      dockerfile: ../../docker/https-endpoint/Dockerfile
  i40-aas-https-endpoint-egress:
    build:
      context: apps/https-endpoint-egress
      network: host
      dockerfile: ../../docker/https-endpoint-egress/Dockerfile
  i40-aas-data-manager:
    build:
      context: apps/data-manager
      network: host
      dockerfile: ../../docker/data-manager/Dockerfile
  i40-aas-registry:
    build:
      context: apps/registry
      network: host
      dockerfile: ../../docker/registry/Dockerfile
  i40-aas-adapter-registry:
    build:
      context: apps/adapter-registry
      network: host
      dockerfile: ../../docker/adapter-registry/Dockerfile
  i40-aas-storage-adapter-mongodb:
    build:
      context: apps/storage-adapter-mongodb
      network: host
      dockerfile: ../../docker/storage-adapter-mongodb/Dockerfile
