---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-skill
  labels:
    app: i40-aas
    service: onboarding-skill
spec:
  ports:
    - targetPort: endpoint
      port: 80
      protocol: TCP
  selector:
    app: i40-aas
    service: onboarding-skill
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-skill
  labels:
    app: i40-aas
    service: onboarding-skill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: onboarding-skill
  template:
    metadata:
      labels:
        app: i40-aas
        service: onboarding-skill
    spec:
      containers:
        - name: service
          image: sapi40/i40-aas-onboarding-skill
          ports:
            - name: endpoint
              containerPort: 3000
          resources:
            limits:
              cpu: 60m
              memory: 410M
            requests:
              cpu: 48m
              memory: 324M
          env:
            - name: ONBOARDING_SKILL_REQUEST_APPROVAL
              value: "false"
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: REGISTRY_URL
            - name: DATA_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: service-addresses
                  key: DATA_MANAGER_URL
          envFrom:
            - secretRef:
                name: data-manager
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: mongodb
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq
---

