---
apiVersion: v1
kind: Service
metadata:
  name: data-manager
  labels: 
    app: i40-aas
    service: data-manager
spec:
  ports:
  - targetPort: endpoint
    port: 80
    protocol: TCP
  selector:
    app: i40-aas
    service: data-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager
  labels: 
    app: i40-aas
    service: data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: data-manager
  template: 
    metadata:
      labels:
        app: i40-aas
        service: data-manager
    spec:
      containers:
      - name: service
        image: sapi40/i40-aas-data-manager
        ports: 
        - name: endpoint
          containerPort: 4000
        resources:
          limits:
            cpu: 50m
            memory: 384M
          requests:
            cpu: 25m
            memory: 273M
        env:
        - name: ADAPTER_REG_URL
          value: "http://adapter-registry:80/adapters"
        - name: ADAPTER_REG_USER
          value: "admin"
        - name: ADAPTER_REG_PASS
          value: "admin"
        - name: DATA_MANAGER_USER
          value: "admin"
        - name: DATA_MANAGER_PASSWORD
          value: "admin"
---
