---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-ingress
  labels:
    service: ingress
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_INGRESS_USER: {{ .Values.core.ingress.user | default .Values.rabbitmq.rabbitmq.username | quote }}
  CORE_INGRESS_PASSWORD: {{ .Values.core.ingress.password | default .Values.rabbitmq.rabbitmq.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-egress
  labels:
    service: egress
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_EGRESS_USER: {{ .Values.core.egress.user | default .Values.rabbitmq.rabbitmq.username | quote }}
  CORE_EGRESS_PASSWORD: {{ .Values.core.egress.password | default .Values.rabbitmq.rabbitmq.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-ingress-http
  labels:
    service: http-ingress
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_INGRESS_HTTP_USER: {{ .Values.core.ingress.http.user | default (randAlphaNum 20) | quote }}
  CORE_INGRESS_HTTP_PASSWORD: {{ .Values.core.ingress.http.password | default (randAlphaNum 20) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-data-manager
  labels:
    service: data-manager
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_DATA_MANAGER_USER: {{ .Values.core.dataManager.user | default (randAlphaNum 20) | quote }}
  CORE_DATA_MANAGER_PASSWORD: {{ .Values.core.dataManager.password | default (randAlphaNum 20) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-registries-adapters
  labels:
    service: adapters-registry
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_REGISTRIES_ADAPTERS_USER: {{ .Values.core.registries.adapters.user | default (randAlphaNum 20) | quote }}
  CORE_REGISTRIES_ADAPTERS_PASSWORD: {{ .Values.core.registries.adapters.password | default (randAlphaNum 20) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-registries-endpoints
  labels:
    service: endpoint-registry
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_REGISTRIES_ENDPOINTS_USER: {{ .Values.core.registries.endpoints.user | default (randAlphaNum 20) | quote }}
  CORE_REGISTRIES_ENDPOINTS_PASSWORD: {{ .Values.core.registries.endpoints.password | default (randAlphaNum 20) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-skills-onboarding-database
  labels:
    service: onboarding-skill
    {{- include "i40-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  SKILLS_ONBOARDING_DATABASE_USER: {{ .Values.skills.onboarding.database.user | default (randAlphaNum 20) | quote }}
  SKILLS_ONBOARDING_DATABASE_PASSWORD: {{ .Values.skills.onboarding.database.password | default (randAlphaNum 20) | quote }}
---