---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-endpoint-registry
  labels:
    service: endpoint-registry
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  ports:
  - targetPort: endpoint
    port: {{ .Values.core.registries.endpoints.port }}
    protocol: TCP
  selector:
    service: endpoint-registry
    {{- include "i40-aas.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-endpoint-registry
  labels:
    service: endpoint-registry
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: endpoint-registry
      {{- include "i40-aas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: endpoint-registry
        {{- include "i40-aas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: endpoint-registry
        image: "{{ .Values.image.repository }}/i40-aas-endpoint-registry:{{ .Values.image.release }}"
        ports:
        - name: endpoint
	  containerPort: {{ .Values.core.registries.endpoints.port }}
	env:
	- name: LOGGING_LOGLEVEL
	  value: {{ .Values.logging.logLevel }}
	- name: LOGGING_LOGOUTPUT
	  value: {{ .Values.logging.logOutput }}
	- name: CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST
	- name: CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT
	  value: {{ .Values.core.registries.endpoints.database.port }}
	- name: CORE_REGISTRIES_ENDPOINTS_DATABASE_NAME
	  value: {{ .Values.core.registries.endpoints.database.name }}
	envFrom:
	- secretRef:
	    name: {{ .Release.Name }}-core-registries-endpoints-database
	- secretRef:
	    name: {{ .Release.Name }}-core-registries-endpoints
	resources:
	  {{- toYaml .Values.resources | nindent 10 }}
	livenessProbe:
          httpGet:
            path: /health
            port: endpoint
          initialDelaySeconds: 600
          periodSeconds: 60
---
