---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-initializer
  labels:
    service: initializer
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: initializer
      {{- include "i40-aas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
	service: initializer
	{{- include "i40-aas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: initializer
	image: "{{ .Values.image.repository }}/i40-aas-initializer:{{ .Values.image.release }}"
	env:
	- name: LOGGING_LOGLEVEL
	  value: {{ .Values.logging.logLevel }}
	- name: LOGGING_LOGOUTPUT
	  value: {{ .Values.logging.logOutput }}
	- name: CORE_BROKER_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_BROKER_HOST
	- name: CORE_BROKER_PORT
	  value: {{ .Values.core.broker.port }}
	- name: CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_REGISTRIES_ENDPOINTS_DATABASE_HOST
	- name: CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT
	  value: {{ .Values.core.registries.endpoints.database.port }}
	- name: CORE_REGISTRIES_ENDPOINTS_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_REGISTRIES_ENDPOINTS_HOST
	- name: CORE_REGISTRIES_ENDPOINTS_PORT
	  value: {{ .Values.core.registries.endpoints.port }}
	- name: CORE_DATA_MANAGER_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_DATA_MANAGER_HOST
	- name: CORE_DATA_MANAGER_PORT
	  value: {{ .Values.core.dataManager.port }}
	- name: APPLICATION_ADAPTERS_MONGODB_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: APPLICATION_ADAPTERS_MONGODB_HOST
	- name: APPLICATION_ADAPTERS_MONGODB_PORT
	  value: {{ .Values.applicationAdapters.mongoDb.port }}
	- name: CORE_REGISTRIES_ADAPTERS_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_REGISTRIES_ADAPTERS_HOST
	- name: CORE_REGISTRIES_ADAPTERS_PORT
	  value: {{ .Values.core.registries.adapters.port }}
	- name: CORE_INGRESS_HTTP_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_INGRESS_HTTP_HOST
	- name: CORE_INGRESS_HTTP_PORT
	  value: {{ .Values.core.ingress.http.port }}
	- name: CORE_INGRESS_GRPC_HOST
	  valueFrom:
	    configMapKeyRef:
	      name: {{ .Release.Name }}-host-collection
	      key: CORE_INGRESS_GRPC_HOST
	- name: CORE_INGRESS_GRPC_PORT
	  value: {{ .Values.core.ingress.grpc.port }}
	volumeMounts:
	- name: scripts
	  mountPath: "/initializer"
	resources:
	  {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: scripts
	optional: true
	configMap:
	  name: {{ .Values.initializer.configMapName }}
---
