---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-storage-adapter-mongodb
  labels: 
    service: storage-adapter-mongodb
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  ports:
  - targetPort: endpoint
    port: {{ .Values.applicationAdapters.mongoDb.port }}
    protocol: TCP
  selector:
    service: storage-adapter-mongodb
    {{- include "i40-aas.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-storage-adapter-mongodb
  labels: 
    service: storage-adapter-mongodb
    {{- include "i40-aas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: storage-adapter-mongodb
      {{- include "i40-aas.selectorLabels" . | nindent 6 }}
  template: 
    metadata:
      labels:
        service: storage-adapter-mongodb
        {{- include "i40-aas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: storage-adapter-mongodb
          image: "{{ .Values.image.repository }}/i40-aas-storage-adapter-mongodb:{{ .Values.image.release }}"
          ports:
          - name: endpoint
	    containerPort: {{ .Values.applicationAdapters.mongoDb.port }}
	  env:
	  - name: LOGGING_LOGLEVEL
	    value: {{ .Values.logging.logLevel | quote }}
	  - name: LOGGING_LOGOUTPUT
	    value: {{ .Values.logging.logOutput | quote }}
	  - name: APPLICATION_ADAPTERS_MONGODB_DATABASE_HOST
	    valueFrom:
	      configMapKeyRef:
		name: {{ .Release.Name }}-host-collection
		key: SKILLS_ONBOARDING_DATABASE_HOST
	  - name: APPLICATION_ADAPTERS_MONGODB_DATABASE_PORT
	    value: {{ .Values.skills.onboarding.database.port | quote }}
	  - name: APPLICATION_ADAPTERS_MONGODB_DATABASE_USER
	    valueFrom:
	      secretKeyRef:
		name: {{ .Release.Name }}-skills-onboarding-database
		key: SKILLS_ONBOARDING_DATABASE_USER
	  - name: APPLICATION_ADAPTERS_MONGODB_DATABASE_PASSWORD
	    valueFrom:
	      secretKeyRef:
		name: {{ .Release.Name }}-skills-onboarding-database
		key: SKILLS_ONBOARDING_DATABASE_PASSWORD
	  - name: APPLICATION_ADAPTERS_MONGODB_DATABASE_NAME
	    value: {{ .Values.skills.onboarding.database.name | quote }}
	  - name: APPLICATION_ADAPTERS_MONGODB_SUBMODELS_COLLECTION
	    value: {{ .Values.applicationAdapters.mongoDb.submodelsCollection | quote }}
	  resources:
	    {{- toYaml .Values.resources | nindent 12 }}
---
