---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-registry
data:
  AIN_ADAPTER_ID: storage-adapter-ain
  MONGO_ADAPTER_ID: storage-adapter-mongodb
  AIN_ADAPTER_SUBMODEL_ID: opc-ua-devices
  MONGO_ADAPTER_SUBMODEL_ID: opc-ua-devices
---
apiVersion: v1
kind: Secret
metadata:
  name: adapter-registry
type: Opaque
stringData:
  ADAPTER_REG_ADMIN_USER: admin
  ADAPTER_REG_ADMIN_PASS: admin
---
apiVersion: v1
kind: Service
metadata:
  name: adapter-registry
  labels: 
    app: i40-aas
    service: adapter-registry
spec:
  ports:
  - targetPort: endpoint
    port: 80
    protocol: TCP
  selector:
    app: i40-aas
    service: adapter-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-registry
  labels: 
    app: i40-aas
    service: adapter-registry
spec:
  selector:
    matchLabels:
      app: i40-aas
      service: adapter-registry
  template: 
    metadata:
      labels:
        app: i40-aas
        service: adapter-registry
    spec:
      containers:
      - name: adapter-registry
        image: sapi40/i40-aas-adapter-registry
        ports: 
        - name: endpoint
          containerPort: 4500
        resources:
          limits:
            cpu: 53m
            memory: 324M
          requests:
            cpu: 48m
            memory: 263M
        env: 
        - name: AIN_ADAPTER_URL
          valueFrom: 
            configMapRefKey:
              name: service-addresses
              key: AIN_ADAPTER_URL
        - name: MONGO_ADAPTER_URL
          valueFrom: 
            configMapRefKey:
              name: service-addresses
              key: MONGO_ADAPTER_URL
        envFrom:
        - secretRef:
            name: adapter-registry
        - secretRef:
            name: endpoint-registry
        - configMapRef:
            name: adapter-registry
        volumeMounts:
        - mountPath: /service/.node-persist
          name: node-persist
  volumeClaimTemplates:
  - metadata:
      name: node-persist
      labels:
        app: i40-aas
        service: adapter-registry
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
---
